import type { Collection } from "./types";

export const collections: Collection[] = [
  {
    id: "ceramica-gres",
    name: "Cerâmica em grês",
    pieces: [
      {
        id: "vaso-estriado",
        title: "Vaso Estriado em Grês",
        material: "Grês esmaltado",
        description:
          "Torneado à mão e queimado em forno a lenha. Estrias marcadas ainda no barro fresco.",
        type: "UNICA",
        priceLabel: "R$ 340",
        weightGrams: 900,
        heightCm: 24,
        widthCm: 18,
        depthCm: 18,
        tone: "tone-1",
      },
      {
        id: "luminaria-argila",
        title: "Luminária de Argila Queimada",
        material: "Argila queimada, vidro soprado",
        description:
          "Cúpula em vidro soprado, base torneada e queimada em forno a lenha. Luz quente, ideal para mesa de canto.",
        type: "UNICA",
        priceLabel: "R$ 410",
        weightGrams: 1800,
        heightCm: 38,
        widthCm: 22,
        depthCm: 22,
        tone: "tone-4",
      },
      {
        id: "tigela-celadon",
        title: "Tigela Celadon",
        material: "Grês esmaltado",
        description: "Esmalte celadon, aplicado em três camadas. Disponível em três tamanhos.",
        type: "VARIANTE",
        variantLabel: "3 tamanhos",
        priceLabel: "R$ 120 – R$ 210",
        weightGrams: 350,
        heightCm: 8,
        widthCm: 14,
        depthCm: 14,
        tone: "tone-3",
      },
      {
        id: "prato-ondulado",
        title: "Prato Raso Ondulado",
        material: "Grês esmaltado",
        description: "Borda ondulada feita a mão, uma a uma — nenhum prato sai igual ao outro.",
        type: "UNICA",
        priceLabel: "R$ 180",
        weightGrams: 420,
        heightCm: 3,
        widthCm: 28,
        depthCm: 28,
        tone: "tone-1",
      },
    ],
  },
  {
    id: "pinturas",
    name: "Pinturas ao entardecer",
    pieces: [
      {
        id: "retrato-entardecer",
        title: "Retrato ao Entardecer",
        material: "Óleo sobre tela",
        description: "Estudo de luz feito ao entardecer, ao vivo, em uma única sessão.",
        type: "UNICA",
        priceLabel: "R$ 890",
        weightGrams: 600,
        heightCm: 50,
        widthCm: 40,
        depthCm: 3,
        sold: true,
        tone: "tone-2",
      },
      {
        id: "aquarela-3",
        title: "Estudo em Aquarela nº3",
        material: "Aquarela sobre papel algodão",
        description: "Parte de uma série de estudos rápidos em aquarela, papel 300g.",
        type: "UNICA",
        priceLabel: "R$ 260",
        weightGrams: 150,
        heightCm: 30,
        widthCm: 21,
        depthCm: 1,
        tone: "tone-2",
      },
    ],
  },
];
